const icon = (name) => ({
  cyber: '<img src="/assets/icon01.jpg" alt="">',
  police: '<img src="/assets/icon02-home.svg" alt="">',
  security: '<img src="/assets/icon03.svg" alt="">',
  military: '<img src="/assets/icon04.svg" alt="">',
  healthcare: '<img src="/assets/icon05.svg" alt="">'
}[name] || '✦');

const services = [
  ['cyber', 'CYBER SECURITY', 'Pharus delivers boutique and bespoke cyber security training packages. Our portfolio covers red-teaming, wireless and web application exploitation. Our trainers have operational government experience and hold both CREST and OSCP credentials.'],
  ['security', 'SECURITY', 'Pharus has international partners and demonstrates successful delivery in planning and managing security solutions to achieve organizational improvements. Our flexibility and the credentials of our personnel ensure that we are vendor agnostic to ultimate long-term solutions as well as response to immediate needs.'],
  ['police', 'POLICING/EMERGENCY SERVICES', 'Pharus delivers high quality training using instructors with current knowledge and skills from emergency services to deal competently and quickly with all emergency situations. All Pharus instructors have international experience.\n\nTraining is provided in realistic training environments and scenarios. We specialise in providing bespoke emergency services training solutions designed to address specific issues and needs related to location, organisations or individuals.'],
  ['military', 'MILITARY', 'Pharus offers a wide range of quality training and support to military personnel including management personnel and operational officers. Pharus understand the importance of subject matter experts in this field and the sensitive nature of this subject. Details of military training courses can be provided on request.'],
  ['healthcare', 'HEALTHCARE MANAGEMENT', 'A range of current healthcare management courses are available and can be customized to suit the context and audience. Subjects such as Healthcare Strategy and Policy, Revenue Cycle Management and Clinical Governance are developed and delivered by instructors with substantial experience and successful track records.']
];

function brand() { return `<a class="brand" href="/" aria-label="Pharus home"><img src="/assets/logo.svg" alt="Pharus Security Consultancy"></a>`; }
function footer(dark = true) { return `<footer class="footer ${dark ? '' : 'footer-light'}">Copyright © 2019 PHARUS. All Rights Reserved. | Design by <a href="https://learnby.work/" target="_blank" rel="noopener noreferrer">Souad</a></footer>`; }
function shell(content, cls='') { return `<main class="page ${cls}">${brand()}<button class="menu-toggle" aria-label="Open navigation" aria-expanded="false"><i></i><i></i><i></i><b>IM</b></button><aside class="menu" aria-hidden="true"><button class="close-menu" aria-label="Close navigation">×</button><nav><a href="/">Home</a><a href="/our-standards/">Our Standards</a><a href="/our-values/">Our Values</a><a href="/our-service/">Our Services</a><a href="/contact-us/">Contact Us</a></nav></aside>${content}</main>`; }
function title(t) { return `<h1 class="page-title">${t}</h1><div class="rule"></div>`; }

function home() { return shell(`<section class="home-left"><div class="city-glow"></div><div class="home-copy"><h2>Pharus Security Consultancy L.L.C (Pharus)</h2><p>Established to assist clients with precision driven solutions, utilizing both human and technical practices Pharus training scenarios have been utilised by many government organisations throughout the world.</p><p>We continue to grow our network through maintaining the quality of our services and the excellence of our training teams.</p><p>Our training meets the highest standards required for both vocational and academic quality in the government sector.</p></div><div class="radar">⌂</div></section><section class="home-right"><div class="home-services"><p>We're the leading, international provider of high-quality consultancy and training in the following field,</p><div class="service-choice">${services.map(([key, label]) => `<span><i>${icon(key)}</i>${label}</span>`).join('')}</div></div>${footer()}</section>`, 'home'); }
function standards() { return shell(`<section class="standards-hero">${title('OUR STANDARDS')}<div class="standards-copy"><article><h3>VISION</h3><p>To grow our reputation as leading experts providing quality and excellence, enabling and empowering our stakeholders in security, military, emergency services and healthcare sectors to achieve the quality and innovative outcomes resulting in continuous improvement.</p></article><article><h3>MISSION STATEMENT</h3><p>As an international consulting and training company specialising in customised solutions for security, military, emergency services and healthcare sectors our responsible consulting and training is based on evidence-based best practice approaches.</p><p>We develop long-term relationships with our customers and cooperation partners based on professionalism and loyalty.<br>We promote the development of our employees by challenging assignments and a value-based leadership.</p><p>We consider and respond to the principles of sustainable development.</p></article></div><div class="standards-photo"></div></section>${footer()}`, 'standards'); }
function values() { return shell(`<section class="values-photo"><div class="handshake"></div><div class="leaf">◒</div></section><section class="values-copy">${title('VALUES')}<p>Our values fully align with our actions, in cooperation with our stakeholders.</p><h3>QUALITY</h3><p>Develop optimized solutions Systematic exploration<br>of partnerships and interdependences</p><h3>INTEGRITY</h3><p>Act honestly, respectfully and responsibly in every relationship.</p></section>${footer()}`, 'values'); }
function serviceItem([key,label,text]) { return `<article class="service-item"><i>${icon(key)}</i><div><h3>${label}</h3>${text.split('\n\n').map(x=>`<p>${x}</p>`).join('')}</div></article>`; }
function servicesPage() { return shell(`<section class="services-intro"><div>${title('OUR SERVICES')}<p>At Pharus we offer an unrivalled range of consultancy, training, and support services delivered to by experts in their fields of military, the security and emergency services. We can combine any areas of interest to produce bespoke training and service packages that incorporate some, or all, of the services tailored to meet the needs of your organization.</p></div><div>${title('TRAINING SERVICES')}<p>Training is a major service provided by Pharus. We are pleased to introduce our extensive range of courses for the security, military, health and emergency services sectors. Courses can be delivered for a variety of venues and can be condensed or expanded to meet specific needs or entirely bespoke. In addition to our training courses we provide training needs analysis in cooperation with job exercises.</p><p>Detailed course information is available as individual documents in English and Arabic. Our training includes the following:</p></div></section><section class="services-list">${services.map(serviceItem).join('')}<div class="deco-health">✱</div></section>${footer(false)}`, 'services'); }
function contact() { return shell(`<section class="contact-content">${title('CONTACT')}<div class="contact-grid"><p>Pharus Security Consultancy L.L.C 1213, Al<br>Manara Tower 3, Business Bay, P.O. Box<br>26342, Dubai - U.A.E.</p><p>T. +971 (4) 311 6563<br>F. +971 (4) 331 8810<br>W. www.pharus-intl.com</p></div></section><div class="contact-watermark">PHĀRUS<small>SECURITY CONSULTANCY</small></div>${footer()}`, 'contact'); }

const routes = {'/':home, '/our-standards/':standards, '/our-values/':values, '/our-service/':servicesPage, '/contact-us/':contact};
function render() { const path = location.pathname.endsWith('/') ? location.pathname : location.pathname + '/'; document.getElementById('app').innerHTML = (routes[path] || home)(); bind(); }
function bind() { const menu=document.querySelector('.menu'), toggle=document.querySelector('.menu-toggle'), close=document.querySelector('.close-menu'); const set=(open)=>{menu.classList.toggle('open',open); toggle.setAttribute('aria-expanded',open); menu.setAttribute('aria-hidden',!open);}; toggle.onclick=()=>set(true); close.onclick=()=>set(false); document.querySelectorAll('a[href^="/"]').forEach(a=>a.onclick=e=>{e.preventDefault();history.pushState({},'',a.getAttribute('href'));render();}); }
window.addEventListener('popstate',render); render();

